version: '3.8'

services:
  greeter:
    image: bavix/greeter-client:1
    depends_on:
      - server
    command:
      - -addr=server:4770
      - -name=gripmock
    networks:
      - bx-greeter

  server:
    image: bavix/greeter-server:1
    ports:
      - 4770:4770
    command:
      - -port=4770
    networks:
      - bx-greeter

networks:
  bx-greeter:
