name: Integration test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Run test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Integration test
        run: docker compose -f docker-compose.test.yaml up --abort-on-container-exit --exit-code-from greeter
